server:
  port: 15051

spring:
  application:
    name: lrpc-provider

lrpc:
  port: 15151
  registry-addr: 127.0.0.1:12181
  registry-type: ZOOKEEPER

eureka:
  client:
    enabled: false